### ISSUE TITLE
Visualization of PET volumes need to be improved: LUT and w/l

### ISSUE THREAD

**Issue by fedorov** [QIICR/Slicer-PETDICOMExtension#1]
SUV volumes should probably have PET-specific lookup table (PET-heat?) and also some window/level pre-set that makes sense for clinicians. @ejulrich do you know if there is a certain way SUV volumes are typically windowed?

**Comment by ejulrich** [comment]
It is common here for SUVbw images (FDG-PET) to be presented with W/L at 6 and 3. This may change for different tracers or SUV types, but it would probably be okay for this to be the default. As for the LUT, I have always used Inverted Grey. I'll have to ask around to see if clinicians would prefer another.

**Comment by fedorov** [comment]
Ethan, it would be great to have this resolved, and it seems like it should not be difficult. Do you need help, when do you think this will be resolved?

**Comment by ejulrich** [comment]
Sorry for the delay on this. A default LUT and W/L has been added for PET images only (DICOM series read using DICOMPETSUVPlugin). The LUT and W/L for series read by DICOMRWVMPlugin have been left generic, because a RWVM does not necessarily need to be for an SUV image.
See commit 2cf75a6f5d9bc842b6dd43f8cc97ee85e70e5591

**Comment by fedorov** [comment]
Thank you Ethan! I have some strange issues with Slicer build, but will confirm once I test, and then we should update the extension in ExtensionIndex.

**Comment by fedorov** [comment]
Ethan, I just tested - looks good!

Few things that should be improved, in my opinion:

1) RWVM plugin should set W/L and LUT in the same way as SUV plugin, since it knows about the quantity (SUV) being encoded
2) as @chribaue pointed out, W/L will depend on the tracer. Does it make sense to add a check for the tracer?

**Comment by ejulrich** [comment]
Here are my thoughts:
1) In our use case, it would not be a problem to have the RWVM plugin set the LUT and W/L. But my thinking was that there could be other RWVM objects that are not associated with PET. Should we always assume the RWVM is for SUV? I figured all the modality-specific operations (like setting the LUT) could be all in one place in the PET SUV plugin.
2) Yes, it would make sense to add a check for the tracer. I think adding this should be straightforward.

**Comment by fedorov** [comment]
Ethan, I agree that for (1) it does not make sense to always set W/L for RWVM plugin. But in those cases when RWVM is used for storing SUV, this can be detected (just check the quantity or units stored in RWVM) and in those cases W/L can be set. Does it make sense? Maybe we can chat about this over phone/hangout if not clear?

**Comment by ejulrich** [comment]
Yes, it makes sense. I should be able to implement this without much effort. Thanks!

**Comment by fedorov** [comment]
Ethan, thanks - this looks great now!

Will you create a pull request for the Slicer ExtensionIndex so that the extension is updated?

**Comment by ejulrich** [comment]
Reference pull request https://github.com/Slicer/ExtensionsIndex/pull/886
