### ISSUE TITLE
Extension is not functional on mac

### ISSUE THREAD

**Issue by fedorov** [QIICR/Slicer-PETDICOMExtension#2]
Steps to reproduce:

1) download QIN-HEADNECK case 73 (screenshot 1)

![image](https://cloud.githubusercontent.com/assets/313942/7799920/1b894b82-02db-11e5-9b58-2d86194926ce.png)

2) try to parse from DICOM module (screenshot 2)

![image](https://cloud.githubusercontent.com/assets/313942/7799923/22598c1a-02db-11e5-85c8-7caff9a533cd.png)

3) error is in screenshot 3

![image](https://cloud.githubusercontent.com/assets/313942/7799927/2b7b3d98-02db-11e5-8556-3b8065151fda.png)

**Comment by fedorov** [comment]
(I think!) I figured out the problem! (but not the solution!)

What happens is I downloaded both PT and CT series from TCIA, and they
were imported into the same directory.

When SUV calculation routine is called, it takes the directory where
the PET series is as input. However, that directory also contains the
CT series.

I think SUV routine attempts to find SUV-required attributes in the CT
instances and fails.

To make the process more robust, the SUV converter should probably
take on input the list of instances, not just the input directory.
This however may cause problems on the operating systems that have
restrictions on the maximum length of the command line, since there
will be a lot of files, and file names may be long....

A potential solution to this could be to pass a text file, or json
file, which would list the input files....

We will probably need to think about this and revisit to find what is
the optimal solution to this problem...

**Comment by chribaue** [comment]
I revised the extension. It is now capable of dealing with extra Dicom files in the same folder. Therefore, the CLI utilizes the PET series instance UID to identify the correct PET scan. The series instance UID is provided by the DICOMPETSUVPlugin based on the user's selection.
