### ISSUE TITLE
Implemented SUV calculation - documentation

### ISSUE THREAD

**Issue by fedorov** [QIICR/Slicer-PETDICOMExtension#3]
Guys, can you confirm - is it correct that this plugin implements the calculation as suggested by QIBA in the document on this page: http://qibawiki.rsna.org/index.php/Standardized_Uptake_Value_(SUV) ?

If yes, I suggest we add a link and explanation to the README. If not - some explanation why not and what are the differences.

What do you think?

**Comment by ejulrich** [comment]
Yes, the [SUVFactorCalculatorCLI](https://github.com/QIICR/Slicer-PETDICOMExtension/tree/master/SUVFactorCalculatorCLI) follows the "Vendor-neutral pseudo-code for SUV calculation - extracted 'happy path only'" [document](http://qibawiki.rsna.org/images/6/60/SUV_vendorneutral_pseudocode_happypathonly_20121015_DAC.doc).

**Comment by ejulrich** [comment]
Updated README 83f0bd9435026984b83f04949fbcd04c65f33c37
