### ISSUE TITLE
Calculation of SUV values

### ISSUE THREAD

**Issue by kiranvaidhya** [QIICR/Slicer-PETDICOMExtension#4]
I believe the calculation for SUV is as follows:

`SUV = PET_activity * weight / decay_corrected_dose`

Your implementation does **NOT** convert the `PET_raw` intensity values (0 to 32767) to `PET_activity` values using `rescale slope` and `rescale intercept` by the following equation: 

`PET_activity = PET_raw * rescale_slope + rescale_intercept`

Can you please verify this and confirm the same? If the issue is valid, can you explain the fundamentals behind your implementation?

**Comment by ejulrich** [comment]
The SUVFactorCalculator determines the SUV conversion factors. The most common is SUVbw (body weight). As you have said, the calculation is:

`SUVbw = PET_activity * weight / decay_corrected_dose`

The [SUVFactorCalculator](https://github.com/QIICR/Slicer-PETDICOMExtension/blob/master/SUVFactorCalculatorCLI/SUVFactorCalculator.cxx#L760) only determines: 

`SUVbwConversionFactor = weight / decay_corrected_dose`.

The `rescale_slope` and `rescale_intercept` should be automatically applied when the DICOM series is read by Slicer and a [volume is created](https://github.com/QIICR/Slicer-PETDICOMExtension/blob/master/DICOMRWVMPlugin/DICOMRWVMPlugin.py#L204). So all that is needed is to apply the SUV conversion factor.

@kvrd18 Does that help?

**Comment by kiranvaidhya** [comment]
Yes. Thanks for the clarification.
